### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by mcollardanuy** [Living-with-machines/T-Res#197]
Link to [checklist](https://aclrollingreview.org/responsibleNLPresearch/).

To do:
- [ ] Add licence or terms information to all used artifacts, both in the paper and in code.
- [ ] Report the number of parameters in the models used, the total computational budget (e.g., GPU hours), and computing infrastructure used.
- [ ] Discuss the experimental setup, including hyperparameter search and best-found hyperparameter values.
- [ ] Report descriptive statistics about your results (e.g., error bars around results, summary statistics from sets of experiments).
- [ ] Discuss whether you are reporting the max, mean, etc. or just a single run.
- [ ] If you used existing packages, report the implementation, model, and parameter settings used.
