### ISSUE TITLE
List resources to release and where

### ISSUE THREAD

**Issue by mcollardanuy** [Living-with-machines/T-Res#232]
## To do:
- [x] Upload NER model to HuggingFace: #193 
- [x] Upload DeezyMatch training set to BL repo: #242 
- [x] Upload NER- and ED- formatted topres19th data to BL repo: #243
- [x] Decide where to upload wikipedia/wikidata resources: #259 

### To run T-Res for the current configuration
```
resources/models/blb_lwm-ner-fine.model/
resources/wikidata/wikidata_gazetteer.csv
resources/wikidata/entity2class.txt
resources/wikidata/mentions_to_wikidata.json
resources/wikidata/mentions_to_wikidata_normalized.json
resources/wikidata/wikidata_to_mentions_normalized.json
resources/deezymatch/combined/wkdtalts_w2v_ocr/
resources/deezymatch/models/w2v_ocr/
resources/rel_db/embeddings_database.db
resources/models/disambiguation/deezymatch+3+25_Ashton1860+wmtops
```
Also, `resources/models/blb_lwm-ner-fine.model/` unless it's uploaded to HF (see [issue](https://github.com/Living-with-machines/T-Res/issues/193)).

### To train a new fine-grained NER model (with topRes19th)
```
experiments/outputs/data/lwm/ner_fine_train.json
experiments/outputs/data/lwm/ner_fine_dev.json
```

### To train a new DeezyMatch model (for English OCR)
```
resources/deezymatch/data/w2v_ocr_pairs.txt
```

### To generate a new DeezyMatch training set (for English OCR)
Nothing, embeddings already uploaded [here](https://zenodo.org/record/7887305#.ZFtnhS8sz0o), store them under `resources/models/w2v/` in folders named `w2v_18XXs_news`, where `XX` is the decade.

### To train a new entity disambiguation model (with topRes19th)
```
experiments/outputs/data/lwm/linking_df_split.tsv
```
