### ISSUE TITLE
Investigate and adapt Radboud Entity Linker

### ISSUE THREAD

**Issue by mcollardanuy** [Living-with-machines/T-Res#66]
Settings:
- [x] Using web API end-to-end (see [comment](https://github.com/Living-with-machines/toponym-resolution/issues/66#issuecomment-1041239692))
- [x] Using web API given the mentions (see [comment](https://github.com/Living-with-machines/toponym-resolution/issues/66#issuecomment-1041245305))
- [x] Using REL locally with the provided data (see [comment](https://github.com/Living-with-machines/toponym-resolution/issues/66#issuecomment-1041284947))
- [x] Use REL locally adapted to our resource (see [comment](https://github.com/Living-with-machines/toponym-resolution/issues/66#issuecomment-1041332411))
    - [x] Only allow disambiguation to geographical entities
    - [x] Recreate wikipedia processing

Integration with our pipeline is in issue #72.

At the moment, I'm running the different options from `/resources/develop/mcollardanuy/REL` in the `toponymVM`.
